# Generated by Django 6.0.3 on 2026-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzaprofitdata',
            options={'verbose_name': 'Pizza Profit', 'verbose_name_plural': 'Pizza Profit'},
        ),
    ]
