# Generated by Django 6.0.3 on 2026-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0002_alter_pizzaprofitdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaArchvSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('pizza_total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_foodpanda_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_daily_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pizza Archived Summary',
                'verbose_name_plural': 'Pizza Archived Summary',
            },
        ),
        migrations.CreateModel(
            name='pizzaSalesArchv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('pizza_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fp_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_date', models.DateField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pizza Sale Archive',
                'verbose_name_plural': 'Pizza Sale Archive',
            },
        ),
        migrations.RenameField(
            model_name='pizzasale',
            old_name='FMP_sale',
            new_name='fp_sale',
        ),
        migrations.RenameField(
            model_name='pizzasale',
            old_name='foodpanda',
            new_name='pizza_sale',
        ),
    ]
