# Generated by Django 6.0.3 on 2026-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSaleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('total_fmp_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_foodpanda_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_daily_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archived Sale Summary',
                'verbose_name_plural': 'Archived Sale Summaries',
            },
        ),
        migrations.CreateModel(
            name='kingsProfitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('totalProfitAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distributionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disburseDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Given', 'Given'), ('Not Given', 'Not Given')], default='Given', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kings Profit Data',
                'verbose_name_plural': 'Kings Profit Data',
            },
        ),
        migrations.CreateModel(
            name='saleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('FMP_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foodpanda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_date', models.DateField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sale Data',
                'verbose_name_plural': 'Sales Data',
            },
        ),
    ]
