# Generated by Django 6.0.3 on 2026-04-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivedSaleSummary',
            new_name='kingsArchvSummary',
        ),
        migrations.RenameModel(
            old_name='kingsProfitData',
            new_name='kingsProfit',
        ),
        migrations.RenameModel(
            old_name='saleData',
            new_name='kingsSale',
        ),
        migrations.AlterModelOptions(
            name='kingsarchvsummary',
            options={'verbose_name': 'Kings Archived Summary', 'verbose_name_plural': 'Kings Archived Summary'},
        ),
    ]
