# Generated by Django 6.0.3 on 2026-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingsapp', '0002_rename_archivedsalesummary_kingsarchvsummary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kingsprofit',
            options={'verbose_name': 'Kings Profit', 'verbose_name_plural': 'Kings Profit'},
        ),
        migrations.AlterModelOptions(
            name='kingssale',
            options={'verbose_name': 'Kings Sale', 'verbose_name_plural': 'Kings Sale'},
        ),
    ]
