# Generated by Django 6.0.3 on 2026-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingsapp', '0003_alter_kingsprofit_options_alter_kingssale_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='kingsSalesArchv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('FMP_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foodpanda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_date', models.DateField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kings Sale Archive',
                'verbose_name_plural': 'Kings Sale Archive',
            },
        ),
    ]
